/** A 3D geographic coordinate: [longitude, latitude, altitude_meters] (SRS §F1.3). */
export type LngLatAlt = [number, number, number];

export interface Station {
  id: number | string;
  name: string;
  nameTh: string;
  code: string;
  position: LngLatAlt;
}

export type Structure = "elevated" | "atGrade" | "underground";
export type VehicleType = "heavy" | "monorail" | "apm" | "commuter";

/**
 * One track vertex: [lng, lat, altitudeMeters, structure].
 *
 * Structure is per-POINT, not per-line (MVP 6): MRT Blue, Orange and Purple
 * Phase 2 all dive underground and surface again within one relation, and
 * SRT Red is genuinely mixed at-grade/elevated. `LineGeometry.structure`
 * survives as the line's DEFAULT — what an untagged way falls back to.
 */
export type TrackPoint = [number, number, number, Structure];

/** One line's rendered geometry, generated by tools/fetch-network.mjs. */
export interface LineGeometry {
  key: string;
  name: string;
  nameTh: string;
  color: string;
  /** Fallback for track points whose OSM way carries no tunnel/bridge/layer. */
  structure: Structure;
  vehicleType: VehicleType;
  /** null = track geometry only, never simulated (pre-revenue or absent feed). */
  gtfsRouteId: string | null;
  /** Under construction / not yet in revenue service — rendered distinctly. */
  preRevenue: boolean;
  /** null for a line fetched by wayNamePattern instead of a route relation. */
  relationId: number | null;
  osmName: string;
  track: TrackPoint[];
  stations: Station[];
}

export interface NetworkData {
  generated: string;
  source: string;
  /** Order is load-bearing: index == cache route_idx == vehicle lane 6. */
  lines: LineGeometry[];
}
