/**
 * Ambient typings for the wasm-pack output (`src/sim/pkg/`, crate
 * `metro-sim-wasm`, built with `--target web`) — see docs/ENGINE_CONTRACT.md §4.
 *
 * The pkg directory is generated by the Rust toolchain and may not exist yet;
 * this declaration keeps the TypeScript program green either way. TypeScript
 * forbids *relative* ambient module names, so a single-wildcard pattern is
 * used — it matches the worker's `import ... from "./pkg/metro_sim_wasm"`.
 * Once the real pkg exists, its own `metro_sim_wasm.d.ts` wins resolution.
 */
declare module "*/pkg/metro_sim_wasm" {
  /** wasm-pack web-target initializer; with no argument it loads
   * `metro_sim_wasm_bg.wasm` via `new URL(..., import.meta.url)`. */
  export default function init(
    module_or_path?: { module_or_path?: unknown } | string | URL,
  ): Promise<unknown>;

  export class Engine {
    constructor(cache_bytes: Uint8Array);
    /** ValidationSummary as JSON (snake_case keys, contract §3/§4). */
    validation_json(): string;
    /** Writes up to MAX_VEHICLES stride-8 records into `out`, returns count. */
    evaluate(date_yyyymmdd: number, sec_of_day: number, out: Float32Array): number;
    /** True if the most recent `evaluate()` hit MAX_VEHICLES and dropped
     * vehicles — call right after `evaluate()`. */
    last_truncated(): boolean;

    // UI-rate schedule queries (contract §7). Keep these in sync with
    // rust-engine/wasm/src/lib.rs — this fallback is what keeps `tsc` honest
    // when src/sim/pkg/ has not been generated.
    /** `RunDetail` as JSON, or "null" when the run is not live. */
    run_detail_json(run_idx: number, date_yyyymmdd: number, sec_of_day: number): string;
    /** `StationBoard` as JSON, or "null" for unknown indices. */
    station_board_json(
      route_idx: number,
      station_idx: number,
      date_yyyymmdd: number,
      sec_of_day: number,
      limit: number,
    ): string;
    /** All stations with ENU positions, as JSON. */
    stations_json(): string;

    /** `RoutePlan` as JSON (camelCase keys — a deliberate deviation from
     * contract §7's snake_case convention, documented there and in
     * CLAUDE.md), or "null" for a structurally invalid request. */
    plan_route_json(
      from_route_idx: number,
      from_station_idx: number,
      to_route_idx: number,
      to_station_idx: number,
      date_yyyymmdd: number,
      sec_of_day: number,
      max_transfers: number,
      max_wait_s: number,
      transfer_buffer_s: number,
    ): string;

    free(): void;
  }
}
